### ISSUE TITLE
Wind data in km/h

### ISSUE THREAD

**Issue by sqpp** [fcambus/ansiweather#137]
Hey,

I prefer the wind data in km/h, but I don't see that option to convert it. Metric settings won't work in this case.

Normally it would be a multiply by 3.6 however, I don't see ways to accomplish that besides of manipulating the output.

**Comment by Heistergand** [comment]
I wrote a patch for that and made a pull request: #145

**Comment by fcambus** [comment]
The SI unit for wind speed is metres per second, and ansiweather will stick to that.

**Comment by Heistergand** [comment]
The SI unit for sind speed isn't imperial as well. But it is an option in ansiweather, because it pays off in the user experience.

Scientifically, there is no point in colorizing the output either. But ansiweather provides this option. It improves user experience.

Providing an option for formatting the output correctly to km/h (despite leaving that to the end-user) is improving the user-xp as well. Sorry, but it's pretty uppity to ignore the user on this one.

**Comment by kevinmatthes** [comment]
I would like to suggest the following:  a completely user-defined preferred unit, built upon m/s.  The configuration could accept a user-defined unit name and a custom multiplication factor.  The example configuration could contain the values for mph as comments such that users might enter the values for their preferred units as they wish; this might be kilometres per hour or parsec per year, for example.  If such an alternative is configured (and activated), it will be the sole unit used for output.  I consider it very likely that people will only use their preferred unit, if available.

I can understand both opinions in the recent discussion.  I consider myself km/h less informative and less representative than m/s but I also understand that users might want to be able to alter the defaults.  This suggestion is in my opinion the best solution for both sides; m/s stays the default, if not altered.  If another unit is intended, people just need to give a new name and to enter the respective calculation factor to automatically override the default.  Furthermore, let us assume that some third unit would be introduced -- the chances that a fourth one, a fifth one and so forth would be requested, as well, are rather high, right?  A generic, optional configuration interface for exactly one further velocity unit would prevent this scenario while still fulfilling the other requirements (m/s stays default, km/h can be configured, mph is still available as example override configuration).

Would this suggestion be suitable?

**Comment by sqpp** [comment]
It's really not about what is informative or not. It's like basics. Just like Celsius. Some countries, regions use Fahrenheit some does Celsius.

**Comment by kevinmatthes** [comment]
Would the suggested configuration interface solve the issue?

**Comment by sqpp** [comment]
Not sure what configuration interface refers too, I would expect to have a true and false switch (boolean) for wind_kmh as simple is that.

**Comment by sqpp** [comment]
That also works, I don't know the logic behind.

**Comment by kevinmatthes** [comment]
@sqpp Okay, thank you.

@fcambus @Heistergand Would this suggestion work for you, as well?

**Comment by Heistergand** [comment]
I'm a little surprised. The parameter design was not the original argument for rejecting this draft.

I already wrote a patch, which actually already is almost as simple as a `true/false` switch. I doubt anyone read it. The patch introduces a new switch and a corresponding config entry for using km/h as parameter, both if omitted fall back to default, which is m/s in context of metric units. For better readability and clearance it also accepts `m/s`. Although that seems redundant, defaults are 'blind options' which I do not recommend as soon as they are not constant anymore. If you prefer a `true/false`, just rename the switches, the logic remains the same. 

So if you asked me wether I would go for `alternative_unit_*`, I'd say no, because in the real world, nobody measures wind speed in parsec per year, but many people can think in km/h and relate to that. 

See, if a tornado smashes that cow through your window, you would probably compare its speed to the one of a car or a train, which in common parlance would probably mean km/h, because that's what people are used to use as unit for speed. Tempo limit signs are not written in m/s as well. If you want to use the output of ansiweather as input for a scientific tool though, I'd answer that the scientific tool should directly connect to the api behind it. (And before we dive into an mph-discussion, let's be clear about this: the vast majority of countries on this globe do not use the imperial system.) 

🎤👊🖐️💥
